# Site settings

title: IsmaelTovar.com
# email: no-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://ismaeltovar.github.io/" # the base hostname & protocol
github_username:  ismaeltovar

# Build settings
theme: beautiful-jekyll-theme
plugins:
  - jekyll-feed

# Exclude from processing.

exclude:
   - .sass-cache/
   - .jekyll-cache/
   - gemfiles/
   - Gemfile
   - Gemfile.lock
   - node_modules/
   - vendor/bundle/
   - vendor/cache/
   - vendor/gems/
   - vendor/ruby/
